

CREATE TABLE t_Fragedef
(
    FragenID INTEGER AUTO_INCREMENT,
    Bez VARCHAR(255),
    PRIMARY KEY(FragenID)
);

CREATE TABLE t_Fachdef
(
    FachID INTEGER AUTO_INCREMENT,
    Fach VARCHAR(30),
    PRIMARY KEY(FachID)
);

CREATE TABLE t_FachFrageDef
(
    FachFrageID INTEGER AUTO_INCREMENT,
    FachID INTEGER,
    FragenID INTEGER,
    PRIMARY KEY(FachFrageID)
    FOREIGN KEY(FragenID) REFERENCES t_Fragedef(FragenID),
    FOREIGN KEY(FachID) REFERENCES t_Fachdef(FachID)
    
);

CREATE TABLE t_Persdef
(
    PersID INTEGER AUTO_INCREMENT,
    PLZ INTEGER,
    PRIMARY KEY(PersID)
);

CREATE TABLE t_umfrage
(
    ID INTEGER AUTO_INCREMENT,
    TST date NOT NULL,
    FragenID INTEGER NOT NULL,
    PersID INTEGER NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(FragenID) REFERENCES t_Fragedef(FragenID),
    FOREIGN KEY(PersID) REFERENCES t_Persdef(PersID)
);
